### ISSUE TITLE
Sample code

### ISSUE THREAD

**Issue by srikarym** [HapeMask/crfrnn_layer#2]
Can you provide a sample lasagne code which uses crf as rnn? I tried to use it in my code in this way but I am unable to get the output as a theano tensor. 

from crfrnn.layers import CRFasRNNLayer
l_in0 = InputLayer(shape=(None, 1, None, None), input_var=input_var0)

conv1 = Conv2DLayer(l_in0, 2, 5,  pad='same', untie_biases=False, W=lasagne.init.GlorotNormal(), b=lasagne.init.Constant(0.), nonlinearity=softmax, flip_filters=True)

crf0 = CRFasRNNLayer(conv1, l_in0)
out = lasagne.layers.get_output(crf0)

**Comment by HapeMask** [comment]
Fixed in 417bbe6d48d1fcd17f0d4f6bde24e51a177ba9df.
